---
title: "Does FDI Drive Growth?"
subtitle: "Evidence from the World Development Indicators"
format: revealjs
author: Lucia Hernandez
---

## Overview

## Data
- The data used in this analysis is from the World Bank Group's World Development Indicators (WDI) Database. It is a comprehensive collection of international development indicators. 

- The UN Trade and Development (UNCTAD) World Investment Report was also used to identify the countries that received the most FDI in 2025.

# Analysis
```{r}
library(tidyverse)
library(knitr)
df0 <- read_csv('WDICSV.csv')
series <- read_csv('WDISeries.csv')
countries <- read_csv('WDICountry.csv')


series <- series %>%
  filter(`Series Code` == 'BX.KLT.DINV.WD.GD.ZS' | 
           `Series Code` == 'NY.GDP.PCAP.KD.ZG' )

df <- df0 %>%
  pivot_longer(
    cols = 5:70,
    names_to = 'year',
    values_to = 'score'
  ) %>%
  filter(`Indicator Code` == 'BX.KLT.DINV.WD.GD.ZS' |
          `Indicator Code` == 'NY.GDP.PCAP.KD.ZG')%>%
  pivot_wider(
    values_from = 'score',
    names_from = `Indicator Code`
  )%>%
  rename(
    fdi = 'BX.KLT.DINV.WD.GD.ZS',
    gdp = 'NY.GDP.PCAP.KD.ZG'
  )%>%
  mutate( year = as.integer(year))%>%
  group_by(`Country Name`, `Country Code`, year) %>%
  summarize(
    fdi = first(na.omit(fdi)),
    gdp = first(na.omit(gdp)), 
    .groups = 'drop'
  )

```


##
```{r}
filter(df, 
  `Country Name` == 'East Asia & Pacific (excluding high income)'| 
  `Country Name` == 'Sub-Saharan Africa (excluding high income)'|
  `Country Name` == 'Latin America & Caribbean (excluding high income)' | 
  `Country Name` == 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)') %>%
    ggplot(aes(fdi,gdp))+
    geom_point(color = 'darkorchid4')+
    geom_smooth(method=lm, color = 'darkorchid4')+
    theme_minimal()+
    theme(plot.title = element_text(size = 12, face = 'bold'))+
    facet_wrap(~`Country Name`, scales = 'free')+
    labs(
    title = 'Figure 1: FDI and GDP per capita in each region',
    subtitle = "1960 - 2025",
      x = "	
Foreign direct investment, net inflows (% of GDP)",
      y = 'GDP per capita (annual % growth)'
)


```

##
```{r}
  
filter(df, `Country Name` == 'Singapore'| `Country Name` == 'Egypt, Arab Rep.'|
         `Country Name` == 'Brazil'|`Country Name` == 'United Arab Emirates')%>%
    ggplot(aes(fdi,gdp))+
    geom_point(color = 'darkorchid4')+
    geom_smooth(method=lm, color = 'darkorchid4')+
    theme_minimal()+
    theme(plot.title = element_text(size = 12, face = 'bold'))+
    facet_wrap(~`Country Name`, scales = 'free')+
    labs(
      title = 'Figure 2: FDI and GDP per capita in the developing economies that received the most FDI per region in 2025',
      subtitle = "1960 - 2025",
      x = "	
Foreign direct investment, net inflows (% of GDP)",
      y = 'GDP per capita (annual % growth)'
    )


```
## 
```{r}
filter(df, 
`Country Name` == 'Least developed countries: UN classification'| 
`Country Name` == 'Low income'|
`Country Name` == 'Lower middle income')%>%
    ggplot(aes(fdi,gdp))+
    geom_point(color = 'darkorchid4')+
    geom_smooth(method=lm, color = 'darkorchid4')+
    theme_minimal()+
    theme(plot.title = element_text(size = 12, face = 'bold'))+
    facet_wrap(~`Country Name`, scales = 'free')+
    labs(
      title = 'Figure 3: FDI and GDP per capita least developed, low income, and middle income countries',
      subtitle = "1960 - 2025",
      x = "	
Foreign direct investment, net inflows (% of GDP)",
      y = 'GDP per capita (annual % growth)'
    )
```
##

```{r}
df2 <- df %>%
  mutate(
    gdp_growth = if_else(gdp>0, "positive","negative"),
    fdi_gr = if_else(fdi > median(fdi, na.rm = T), "High FDI", "Low FDI"),
    fdi_group = fct_relevel(fdi_gr, "Low FDI", "High FDI"))

  

df2 %>%
  filter(!is.na(fdi), !is.na(gdp_growth))%>%
  group_by(gdp_growth)%>%
  summarize(
    n = n(),
    mean_fdi = mean(fdi, na.rm =T),
    median_fdi = median(fdi, na.rm =T)
  )%>%
  kable(digits = 2,
        caption = 'Table 1: Average FDI by GDP Growth Direction',
        col.names = c('Growth Direction', "N", "Mean FDI", "Median FDI"))
```  


## 
```{r}

df2 %>%
  filter(!is.na(fdi_group), !is.na(gdp_growth)) %>%
    group_by(fdi_group, gdp_growth) %>%
    summarize(n = n()) %>%
    ungroup()%>%
    group_by(fdi_group) %>%
    mutate(prop = n / sum(n)) %>%
    ggplot(aes(x = fdi_group, y = prop, fill = gdp_growth)) +
    geom_col() +
    scale_fill_manual(values = c("negative" = "tomato", 
                                 "positive" = "darkorchid4")) +
    scale_y_continuous(labels = scales::percent) +
    theme_minimal() +
    theme(plot.title = element_text(size = 12, face = 'bold'))+
    labs(
      title = "Figure 4: Proportion of Country-Years with Positive vs. Negative GDP Growth",
      subtitle = "By FDI Group",
      x = "FDI Group",
      y = "Proportion of Country-Years",
      fill = "GDP Growth"
    )


```


